# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db  # MongoDB verilerini kalıcı yapar

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: my-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH: false
      
  redis:
      image: redis:latest
      container_name: my-redis
      ports:
        - "6379:6379"

volumes:
  mongo-data:  # Mongo verisi burada kalır